### PR TITLE
useless cors headers

### PR DESCRIPTION
**Pull request by huanzhang**
解决了，删除aliyun oss不需要的headers后遗留的bug。

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@huanzhang Whats the real intention behind this?

Why we don't need those headers anymore?

**Comment by huanzhang** [comment]
@plribeiro3000 Good to see your response:)
According to Aliyun OSS document https://help.aliyun.com/document_detail/26847.html?spm=5176.doc26844.6.240.htEjdt which is like AWS S3, setting CORS for object can only be done through options_object (similar with http://docs.aws.amazon.com/AmazonS3/latest/API/RESTOPTIONSobject.html). 

From the doc, I admit that 'Origin' could still be useful(but useless for 'Access-Control-Allow-Origin'), however, I still want to delete it for the two reasons:
1. we have deleted 'origin' attribute from Fog::Storage::Aliyun::File within the commit aa42195737 which actually introduced a bug at line 107 and line 108
2. we don't have options_object request for now, and the 'origin' header can be added within this new feature in the future

**Comment by plribeiro3000** [comment]
@huanzhang Agreed. Could you take a look at the broken build?
Once is fixed i will gladly merge it.

**Comment by huanzhang** [comment]
fixed:)

**Comment by plribeiro3000** [comment]
We need to get rid of this tests and add real tests.

I've already saw some really complex pieces of code in here and the code coverage is 0%. =s

**Comment by huanzhang** [comment]
Yes, I agree. I'd like to take the storage part :-)

**Pull request merged**
