### PR TITLE
Add support for key_pairs

### PR DESCRIPTION
**Pull request by upadhyeammit**
I am combing all key_pairs related changes in on this PR

This adds import_key_pairs, create_key_pair, describe_key_pair and destroy_key_pair request and these all are supported with key_pair model and collection.

### CODE REVIEW

**Comment by upadhyeammit** [comment]
@dengqinsi request you to review this PR

**Comment by upadhyeammit** [comment]
@plribeiro3000 request you to help on reviewing and merging PR.

Thank You !

**Comment by upadhyeammit** [comment]
@xiaozhu36 request to review, thank you !

**Comment by xiaozhu36** [comment]
Hi @upadhyeammit I am sorry for late reply. Please fix the conflicts.

**Pull request closed without merging**
