### PR TITLE
add bootstrap,destroy,start, stop methods

### PR DESCRIPTION
**Pull request by upadhyeammit**
This adds,
1. The bootstrap method in servers collection, to create and start the instance with arguments.
2. Adds start, stop, reboot, stopped?, running? method in server model to support bootstrapping.
3. Also having destroy method in server model which handles stopping instance before deletion.

### CODE REVIEW

**Comment by upadhyeammit** [comment]
As I have introduced bootstrap method in this commit, I have extended it further to handle assignment of public ipaddress when :max_bandwidth_out is not empty and user has passed :assign_public_ip address attribute.

**Comment by upadhyeammit** [comment]
This PR now depends on https://github.com/fog/fog-aliyun/pull/48 because of method allocate_public_ip_address.

**Comment by upadhyeammit** [comment]
@plribeiro3000 request you to help on reviewing and merging PR.

Thank You !

**Comment by xiaozhu36** [comment]
HI @upadhyeammit Please fix the conflict at first.

**Pull request closed without merging**
