### PR TITLE
recommit to add author info

### PR DESCRIPTION
**Pull request by janehyt**
1. add some methods which related to authorize_security_group and revoke_security_group

2. complete security_group_rule model

### CODE REVIEW

**Comment by janehyt** [comment]
@plribeiro3000 I have done with the author info.

**Comment by plribeiro3000** [comment]
:+1: 

@janehyt One last rebase please?

**Comment by janehyt** [comment]
@plribeiro3000 sorry, I don't know how to rebase remote branch, and I'm sure the develop branch is uptodate, nothing confilct to the master brahch of fog/aliyun

**Comment by plribeiro3000** [comment]
Ops. sorry. I meant squash. =)

**Pull request closed without merging**
